name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make build
    
    - name: Test
      run: |
        cd ./config/
        FOO=bar go test -v -run ./*_test.go
