name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make build
    
    - name: Test
      run: |
        FOO=bar go test -v -run ./config/config_test.go ./config/config.go ./config/*.go
