name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: make build
    
    - name: Test
      run: |
        ls
        pwd
        go test -v -run ./config/config_test.go
